# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: black
        name: Run black
        entry: ./scripts/format.sh
        language: script
    -   id: check-tests
        name: Check tests
        entry: ./scripts/run_tests.sh
        language: script
