version: '3.8'

services:
    ocr:
        platform: linux/x86_64
        image: readable/ocr:latest
        privileged: false
        networks:
            - backend
        environment:
            - WORKER_ID=1
            - API_ENDPOINT=http://api:8081
            - OUTPUT_PATH=/opt/storage
            - SLEEP_TIME=10
            - LOG_LEVEL=INFO
            - MAX_NUM_PAGES=1000
            - NUM_PROC=2
            - DUMP_JSON=1
            - SPACY_MODEL=ro_legal_fl
            - VECTOR_SEARCH=True  
        volumes:
            - /opt/storage:/opt/storage
        tty: true
        command: python3 ocr_worker.py
        deploy:
          resources:
              limits:
                cpus: '3'
                memory: 3072M
              reservations:
                cpus: '2'
                memory: 2048M

volumes:
  ocr_data:
    driver: local
    driver_opts:
      type: none
      device: /opt/storage
      o: bind

networks:
  backend:
    name: api_default
    external: true

