version: '3.8'

services:
    ocr:
        platform: linux/x86_64
        image: readable/ocr:worker
        privileged: false
        environment:
            - WORKER_ID=1
            - API_URL=http://3.229.101.152:8081
            - OUTPUT_PATH=/opt/storage/analysis
            - SLEEP_TIME=10
        volumes:
            - /opt/storage:/opt/storage
        tty: true
        command: python3 ocr_worker.py
volumes:
  ocr_data:
    driver: local
    driver_opts:
      type: none
      device: /opt/storage
      o: bind
