version: '3.8'

services:
    ocr:
        build:
            context: .
            dockerfile: ./Dockerfile
        privileged: false
        volumes:
            - .:/app
        tty: true
        ports:
            - "8080:8080"
        command: bash "./scripts/start-dev.sh"

