version: '3.8'

services:
    ocr:
        platform: linux/x86_64
        image: readable/ocr:latest
        privileged: false
        restart: on-failure
        networks:
            - backend
        environment:
            - WORKER_ID=1
            - API_ENDPOINT=http://api:8081
            - OUTPUT_PATH=/opt/storage/analysis
            - SLEEP_TIME=10
            - LOG_LEVEL=INFO
            - MAX_NUM_PAGES=2000
            - NUM_PROC=1
        volumes:
            - /opt/storage:/opt/storage
        tty: true
        command: python3 ocr_worker.py
        deploy:
          resources:
              limits:
                cpus: '1'
                memory: 1024M
              reservations:
                cpus: '0.5'
                memory: 512M

volumes:
  ocr_data:
    driver: local
    driver_opts:
      type: none
      device: /opt/storage
      o: bind

networks:
  backend:
    name: api_default
    #external: true
