name: Continuous integration and deployment
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Extract branch name
        shell: bash
        run: |
            echo ${GITHUB_HEAD_REF-${GITHUB_REF##*/}}
            echo ${GITHUB_REF##*/}
            echo "##[set-output name=branch;]$(echo ${GITHUB_HEAD_REF-${GITHUB_REF##*/}})"
        id: extract_branch

      - name: Build
        run: |
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ocr:${{ steps.extract_branch.outputs.branch }} .

      - name: Test
        run: |
            docker run -it ${{ secrets.DOCKERHUB_USERNAME }}/ocr:${{ steps.extract_branch.outputs.branch }} ./scripts/run_tests.sh

      - name: Push
        run: |
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/ocr:${{ steps.extract_branch.outputs.branch }}
 

