name: Continuous integration and deployment
on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract branch name
        shell: bash
        run: |
            echo "Branch name ${GITHUB_HEAD_REF-${GITHUB_REF##*/}}"
            echo "Ref name ${GITHUB_REF##*/}"

      - name: Build
        shell: bash
        run: |
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ocr:${GITHUB_HEAD_REF-${GITHUB_REF##*/}} .

      - name: Test
        shell: bash
        run: |
            docker run ${{ secrets.DOCKERHUB_USERNAME }}/ocr:${GITHUB_HEAD_REF-${GITHUB_REF##*/}} ./scripts/run_tests.sh

      - name: Push
        shell: bash
        run: |
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/ocr:${GITHUB_HEAD_REF-${GITHUB_REF##*/}}
