name: Continuous integration and deployment
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Make a previous version
        run: |
            echo ${GITHUB_HEAD_REF-${GITHUB_REF##*/}}
            echo ${GITHUB_REF##*/}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ocr:latest && \
            docker tag ${{ secrets.DOCKERHUB_USERNAME }}/ocr:latest ${{ secrets.DOCKERHUB_USERNAME }}/ocr:previous && \
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/ocr:previous
  
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ocr:main


  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull
        shell: bash
        run: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ocr:main

      - name: Test
        shell: bash
        run: |
            docker run ${{ secrets.DOCKERHUB_USERNAME }}/ocr:main ./scripts/run_tests.sh

      - name: Tag and Push latest
        shell: bash
        run: |
            docker tag ${{ secrets.DOCKERHUB_USERNAME }}/ocr:main ${{ secrets.DOCKERHUB_USERNAME }}/ocr:latest && \
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/ocr:latest

 

  deploy:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.CI_OCR_PR_KEY }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
  
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.CI_OCR_SSH_HOST }} >> ~/.ssh/known_hosts
  
      - name: Pull and deploy
        run: ssh ${{ secrets.CI_OCR_SSH_USER }}@${{ secrets.CI_OCR_SSH_HOST }} "cd /common/anap/ocr && git pull && ./scripts/pull_and_deploy.sh docker-compose_api.yml"
